# Generated by Django 3.0.2 on 2020-04-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='des',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('img1', models.ImageField(null=True, upload_to='pics')),
                ('img2', models.ImageField(null=True, upload_to='pics')),
                ('img3', models.ImageField(null=True, upload_to='pics')),
                ('img4', models.ImageField(null=True, upload_to='pics')),
                ('descrip', models.CharField(max_length=200, null=True)),
                ('big_descrip', models.CharField(max_length=900, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
