# Generated by Django 3.0.2 on 2020-04-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='des',
            name='place_under',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
