# Generated by Django 3.0.2 on 2020-04-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_des_place_under'),
    ]

    operations = [
        migrations.AddField(
            model_name='des',
            name='total_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='des',
            name='total_night',
            field=models.IntegerField(null=True),
        ),
    ]
