# Generated by Django 3.0.2 on 2020-04-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0005_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
