# Generated by Django 3.0.2 on 2020-04-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0007_auto_20200423_2131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='com',
            new_name='comment',
        ),
    ]
