# Generated by Django 3.0.2 on 2020-04-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0008_auto_20200423_2133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
